<a href="https://colab.research.google.com/github/KrupalVasani/Machine-Learning/blob/main/Accuracy_%2CConfusion_Matrix%2C_Precision%2C_Recall_and_F1_Score.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [22]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.datasets import load_iris

In [23]:
knn=KNeighborsClassifier()
iris=load_iris()
x=iris['data']
y=iris['target']

In [24]:
# Accuracy score function
def my_accuracy_score(predicted_y,test_y):
  diff=0
  n=predicted_y.size
  for i in range(0,n,1):
    if(predicted_y[i]==test_y[i]):
      diff+=1
  return (diff/n)

def getIndex(mylist,value):
  n=len(mylist)
  for i in range(0,n-1):
    if(mylist[i]==value):
      return i
  return -1

# Confusion matrix function
def my_confusion_matrix(predicted_y,actual_y):
  classes_count=0
  n=len(test_y)
  classes=[]
  #find classes from actual target array
  for i in range(n):
    if test_y[i] in classes:
      idk=1
    else:
      classes.append(test_y[i])
      classes_count+=1    
  matrix=np.zeros((classes_count,classes_count))
  for j in range(0,n-1):
    matrix[getIndex(classes,predicted_y[j])][getIndex(classes,actual_y[j])]+=1
  
  total_predicted=[]
  total_actual=[]

  for i in range(classes_count):
    temp=0
    temp1=0
    for j in range(classes_count):
      temp +=matrix[i][j]
      temp1 +=matrix[j][i]
    total_actual.append(temp)
    total_predicted.append(temp1)

  columns_name=['Precision','Recall',"F1-Score"]
  my_classification_score=pd.DataFrame(columns=columns_name,data=np.zeros((classes_count,3)),index=classes)
  for i in range(classes_count):
    precision=matrix[i][i]/total_predicted[i]
    recall=matrix[i][i]/total_actual[i]
    #Harmonic mean of both
    f1_score=(2*precision*recall)/(precision+recall)
    my_classification_score.iloc[i,0]=precision
    my_classification_score.iloc[i,1]=recall
    my_classification_score.iloc[i,2]=f1_score
  print(my_classification_score,"\n\n")

  return matrix  

train_x, test_x, train_y, test_y = train_test_split(x,y,test_size=0.3,random_state=30)
knn.fit(train_x,train_y)
predicted_y=knn.predict(test_x)

accuracy=my_accuracy_score(predicted_y,test_y)
print('Accuracy: ',accuracy,'\n')

matrix=my_confusion_matrix(predicted_y,test_y)

print('Confusion Matrix :\n')
print(matrix)

Accuracy:  0.9333333333333333 

   Precision    Recall  F1-Score
0   1.000000  1.000000  1.000000
2   0.944444  0.894737  0.918919
1   0.846154  0.916667  0.880000 


Confusion Matrix :

[[13.  0.  0.]
 [ 0. 17.  2.]
 [ 0.  1. 11.]]
